spring:
  application:
    name: apollo-configservice
  profiles:
    active: github
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

ctrip:
  appid: 100003171

server:
  port: 8080

logging:
  file: /opt/logs/100003171/apollo-configservice.log
